
import { Job, TalentProfile, DashboardStats, ScreeningRun } from '@/app/types';

export const mockJobs: Job[] = [
  {
    _id: '1',
    jobId: 'JOB-001',
    title: 'Backend Engineer – AI Systems',
    description: 'Build scalable APIs and AI-powered features for our HR platform. You will work with Gemini API integrations and design robust microservices.',
    location: 'Kigali, Rwanda',
    employmentType: 'Full-time',
    requiredSkills: ['Node.js', 'Python', 'REST API', 'Database Design'],
    preferredSkills: ['Gemini API', 'AWS', 'Docker'],
    minYearsExperience: 3,
    requiredEducation: "Bachelor's in CS or related",
    softSkills: ['Problem-solving', 'Communication'],
    postedDate: '2025-01-10',
    status: 'open',
    applicantCount: 47,
    createdAt: '2025-01-10T09:00:00Z',
  },
  {
    _id: '2',
    jobId: 'JOB-002',
    title: 'Full-Stack Developer',
    description: 'Join our product team to build next-generation talent marketplace features. React + Node.js stack with MongoDB.',
    location: 'Nairobi, Kenya',
    employmentType: 'Full-time',
    requiredSkills: ['React', 'Node.js', 'TypeScript', 'MongoDB'],
    preferredSkills: ['GraphQL', 'Redis', 'Docker'],
    minYearsExperience: 2,
    requiredEducation: "Bachelor's in CS or related",
    softSkills: ['Teamwork', 'Agile mindset'],
    postedDate: '2025-01-12',
    status: 'screening',
    applicantCount: 102,
    createdAt: '2025-01-12T10:30:00Z',
  },
  {
    _id: '3',
    jobId: 'JOB-003',
    title: 'Data Engineer',
    description: 'Design and maintain data pipelines for analytics and ML model training. Experience with large datasets required.',
    location: 'Remote',
    employmentType: 'Contract',
    requiredSkills: ['Python', 'SQL', 'Apache Spark', 'PostgreSQL'],
    preferredSkills: ['dbt', 'Airflow', 'AWS'],
    minYearsExperience: 4,
    requiredEducation: "Bachelor's in CS, Data Science or related",
    softSkills: ['Analytical thinking', 'Attention to detail'],
    postedDate: '2024-12-20',
    status: 'closed',
    applicantCount: 89,
    createdAt: '2024-12-20T08:00:00Z',
  },
  {
    _id: '4',
    jobId: 'JOB-004',
    title: 'Frontend Engineer',
    description: 'Craft beautiful, accessible interfaces for our recruiter-facing platform. Tailwind CSS, Next.js, and strong design sensibility required.',
    location: 'Kampala, Uganda',
    employmentType: 'Full-time',
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js'],
    preferredSkills: ['Figma', 'Storybook', 'Cypress'],
    minYearsExperience: 2,
    requiredEducation: "Bachelor's in CS or related",
    softSkills: ['Design eye', 'Communication'],
    postedDate: '2025-01-15',
    status: 'open',
    applicantCount: 33,
    createdAt: '2025-01-15T11:00:00Z',
  },
];

export const mockCandidates: TalentProfile[] = [
  {
    _id: 'c1',
    firstName: 'Jean',
    lastName: 'Mukama',
    email: 'jean.mukama@example.com',
    headline: 'Backend Engineer | Specialized in Node.js & Python',
    bio: 'Passionate developer with 5 years of experience in scalable systems.',
    location: 'Kigali, Rwanda',
    skills: [
      { name: 'Node.js', level: 'Expert', yearsOfExperience: 5 },
      { name: 'Python', level: 'Advanced', yearsOfExperience: 4 },
      { name: 'REST API', level: 'Expert', yearsOfExperience: 5 },
      { name: 'MongoDB', level: 'Advanced', yearsOfExperience: 3 },
    ],
    experience: [
      {
        company: 'TechStart Rwanda',
        role: 'Senior Backend Engineer',
        startDate: '2022-03',
        endDate: 'Present',
        description: 'Led API architecture for a SaaS platform serving 50k users.',
        technologies: ['Node.js', 'Python', 'MongoDB'],
        isCurrent: true,
      },
    ],
    education: [
      {
        institution: 'University of Rwanda',
        degree: "Bachelor's",
        fieldOfStudy: 'Computer Science',
        startYear: 2016,
        endYear: 2020,
      },
    ],
    projects: [
      {
        name: 'Project Alpha',
        description: 'Microservices API platform',
        technologies: ['Node.js', 'Docker', 'AWS'],
        role: 'Lead Developer',
        startDate: '2023-01',
        endDate: '2023-08',
      },
    ],
    availability: { status: 'Available', type: 'Full-time' },
    appliedJobs: ['JOB-001', 'JOB-002'],
  },
  {
    _id: 'c2',
    firstName: 'Amina',
    lastName: 'Niyonzima',
    email: 'amina.n@example.com',
    headline: 'Full-Stack Developer | React + Node.js',
    bio: 'Frontend-leaning full stack dev, 3 years building product at startups.',
    location: 'Nairobi, Kenya',
    skills: [
      { name: 'React', level: 'Advanced', yearsOfExperience: 3 },
      { name: 'TypeScript', level: 'Advanced', yearsOfExperience: 2 },
      { name: 'Node.js', level: 'Intermediate', yearsOfExperience: 2 },
      { name: 'MongoDB', level: 'Intermediate', yearsOfExperience: 2 },
    ],
    experience: [
      {
        company: 'DevHub Africa',
        role: 'Full-Stack Developer',
        startDate: '2021-06',
        endDate: 'Present',
        description: 'Built and shipped 4 products from scratch.',
        technologies: ['React', 'Node.js', 'TypeScript'],
        isCurrent: true,
      },
    ],
    education: [
      {
        institution: 'Strathmore University',
        degree: "Bachelor's",
        fieldOfStudy: 'Software Engineering',
        startYear: 2017,
        endYear: 2021,
      },
    ],
    projects: [],
    availability: { status: 'Open to Opportunities', type: 'Full-time' },
    appliedJobs: ['JOB-002'],
  },
];

export const mockScreeningRun: ScreeningRun = {
  _id: 'sr1',
  screeningRunId: 'RUN-20250113143022',
  job: mockJobs[1],
  jobId: 'JOB-002',
  total_evaluated: 102,
  successful_evaluations: 98,
  failed_evaluations: 4,
  timestamp: '2025-01-13T14:30:22Z',
  status: 'completed',
  shortlist: [
    {
      candidateId: 'Jean_Mukama',
      jobId: 'JOB-002',
      rank: 1,
      matchScore: 92,
      strengths: ['Expert Node.js with 5 years hands-on experience', 'REST API design & microservices architecture'],
      gaps: ['No GraphQL experience listed', 'Docker experience could not be confirmed'],
      recommendation: 'Strong Yes',
      reasoning: 'Strong technical alignment with required stack. Extensive API experience directly relevant.',
      explanation: 'Jean brings deep backend expertise in Node.js and Python with documented production experience at scale. Limited GraphQL experience is a minor gap given strong REST mastery. Recommend a technical interview focused on system design.',
      evaluationStatus: 'success',
      candidate: mockCandidates[0],
    },
    {
      candidateId: 'Amina_Niyonzima',
      jobId: 'JOB-002',
      rank: 2,
      matchScore: 78,
      strengths: ['React Advanced with 3 years experience', 'TypeScript proficiency across frontend and backend'],
      gaps: ['Node.js at Intermediate level – may need mentorship for senior tasks', 'MongoDB experience is limited'],
      recommendation: 'Yes',
      reasoning: 'Solid full-stack profile with good product-building track record.',
      explanation: 'Amina is a strong React developer with growing backend skills. The Node.js gap is worth exploring but her TypeScript proficiency and product instincts are valuable. Recommend a take-home coding challenge.',
      evaluationStatus: 'success',
      candidate: mockCandidates[1],
    },
    {
      candidateId: 'David_Kamali',
      jobId: 'JOB-002',
      rank: 3,
      matchScore: 71,
      strengths: ['4 years experience in TypeScript', 'Strong SQL and database design background'],
      gaps: ['Limited React experience – mostly Vue.js projects', 'No MongoDB listed in stack'],
      recommendation: 'Yes',
      reasoning: 'Good technical foundation but frontend stack mismatch needs clarification.',
      explanation: 'David shows strong TypeScript and backend skills. The React gap is notable for this role but his overall development maturity is high. Recommend screening call to assess adaptability.',
      evaluationStatus: 'success',
    },
    {
      candidateId: 'Marie_Habimana',
      jobId: 'JOB-002',
      rank: 4,
      matchScore: 65,
      strengths: ['2 years React experience with modern hooks', 'Previous startup experience brings product thinking'],
      gaps: ['Limited Node.js experience (< 1 year)', 'No TypeScript usage mentioned'],
      recommendation: 'Maybe',
      reasoning: 'Frontend strong but backend gaps are significant for a full-stack role.',
      explanation: 'Marie shows promise on the frontend but backend skills need development. If the role can accommodate some ramp-up time, she may be worth considering.',
      evaluationStatus: 'success',
    },
    {
      candidateId: 'Khalid_Rutayisire',
      jobId: 'JOB-002',
      rank: 5,
      matchScore: 60,
      strengths: ['Node.js experience in production environments', 'Agile/Scrum certified'],
      gaps: ['React experience appears outdated (class components only)', 'TypeScript not mentioned'],
      recommendation: 'Maybe',
      reasoning: 'Backend skills are relevant but frontend stack needs updating.',
      explanation: 'Khalid has solid backend fundamentals but the React skills may need refreshing. Worth a quick technical screening call.',
      evaluationStatus: 'success',
    },
  ],
};

export const mockDashboardStats: DashboardStats = {
  totalJobs: 4,
  openJobs: 2,
  screeningJobs: 1,
  closedJobs: 1,
  totalCandidates: 271,
  totalScreeningRuns: 1,
  recentActivity: [
    {
      id: '1',
      type: 'screening_completed',
      title: 'Screening completed',
      subtitle: 'Full-Stack Developer — 98 candidates evaluated',
      timestamp: '2025-01-13T14:30:22Z',
    },
    {
      id: '2',
      type: 'job_created',
      title: 'New job posted',
      subtitle: 'Frontend Engineer — Kampala, Uganda',
      timestamp: '2025-01-15T11:00:00Z',
    },
    {
      id: '3',
      type: 'screening_started',
      title: 'Screening started',
      subtitle: 'Backend Engineer – AI Systems',
      timestamp: '2025-01-13T09:00:00Z',
    },
    {
      id: '4',
      type: 'job_closed',
      title: 'Job closed',
      subtitle: 'Data Engineer — 89 applicants',
      timestamp: '2025-01-08T16:00:00Z',
    },
  ],
};